- name: Install required packages
  apt:
    name: curl
    state: present
    update_cache: yes

- name: Disable swap (Kubernetes requirement)
  shell: |
    swapoff -a
    sed -i '/ swap / s/^/#/' /etc/fstab
  become: true

- name: Install k3s on master
  when: inventory_hostname in groups['masters']
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} \
      K3S_TOKEN={{ token }} \
      INSTALL_K3S_EXEC="server --cluster-init --tls-san {{ ansible_host }}" \
      sh -
  args:
    creates: /usr/local/bin/k3s
  become: true

- name: Install k3s on worker
  when: inventory_hostname in groups['workers']
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} \
      K3S_URL=https://{{ groups['masters'][0] }}:6443 \
      K3S_TOKEN={{ token }} \
      sh -
  args:
    creates: /usr/local/bin/k3s-agent
  become: true
